targets:
  debian-7: &debian
    build_dependencies:
      - libpam0g-dev
  debian-8:
    <<: *debian
  ubuntu-12.04:
    <<: *debian
  ubuntu-14.04:
    <<: *debian
  ubuntu-16.04:
    <<: *debian
    build_dependencies:
      - git
  centos-6: &el
    build_dependencies:
      - pam-devel
      # required for go buildpack
      - perl-Digest-SHA